In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5,6],np.int8)

In [3]:
arr

array([1, 2, 3, 4, 5, 6], dtype=int8)

In [4]:
arr[0]

np.int8(1)

# Get Shape of array

In [5]:
arr.shape

(6,)

In [6]:
arr.dtype

dtype('int8')

In [7]:
arr[0] = 100

In [8]:
arr

array([100,   2,   3,   4,   5,   6], dtype=int8)

#  5 types you can make an array

1. from other data

In [9]:
listarr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [10]:
listarr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
listarr.size

9

In [12]:
listarr.dtype

dtype('int64')

In [13]:
listarr.shape

(3, 3)

In [14]:
zero = np.zeros((2,5))

In [15]:
zero

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
rn = np.arange(15)

In [17]:
rn

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

**Equallyy n spaced nos form 1 to n**

In [18]:
lspace = np.linspace(1,5,12)

In [19]:
lspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

**Empty array**

In [20]:
emp = np.empty((4,6))

In [21]:
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        8.90095411e-307, 1.89146896e-307, 7.56571288e-307],
       [3.11525958e-307, 1.24610723e-306, 1.37962320e-306,
        1.29060871e-306, 2.22518251e-306, 1.33511969e-306],
       [1.78022342e-306, 1.05700345e-307, 3.11525958e-307,
        1.69118108e-306, 8.06632139e-308, 1.20160711e-306],
       [1.69119330e-306, 1.29062229e-306, 1.24610383e-306,
        9.79094970e-307, 7.56599128e-307, 2.22522596e-306]])

In [22]:
emp = np.empty_like(lspace)

In [23]:
emp

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

**identity matrix**

In [24]:
iden = np.identity(3)

In [25]:
iden

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

**reshape**

In [26]:
arr = np.arange(45)

In [27]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44])

In [28]:
arr.shape

(45,)

In [29]:
arr.reshape(9,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44]])

In [30]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44])

**axis**

In [31]:
x = [[1,2,3],[4,5,6],[7,8,9]]

In [32]:
ar = np.array(x)


In [33]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
ar.sum(axis = 0)

array([12, 15, 18])

In [35]:
ar.sum()

np.int64(45)

**Transpose**


In [36]:
ar.T


array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [37]:
for item in ar :
    print(item)

[1 2 3]
[4 5 6]
[7 8 9]


In [38]:
for item in ar.flat :
    print(item)

1
2
3
4
5
6
7
8
9


In [39]:
ar.ndim #no of dimensions

2

In [40]:
ar.size

9

In [41]:
ar.nbytes #no of bytes

72

In [42]:
y = np.array([1,2,3,4,56,76,78,35,57])

In [43]:
y.argmax()  #index of max element

np.int64(6)

In [44]:
y.argmin()

np.int64(0)

In [45]:
y.argsort()  #array of sotred indices

array([0, 1, 2, 3, 7, 4, 8, 5, 6])

In [46]:
ar.argmax(axis=0)

array([2, 2, 2])

In [47]:
ar.argsort(axis = 0)

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2]])

In [48]:
ar1 = np.array([[1,2,3],[4,5,6],[7,8,9]])

ar2 = np.array([[1,2,1],[5,4,2],[7,6,4]])

In [49]:
ar1+ar2

array([[ 2,  4,  4],
       [ 9,  9,  8],
       [14, 14, 13]])

In [50]:
ar1*ar2

array([[ 1,  4,  3],
       [20, 20, 12],
       [49, 48, 36]])

In [51]:
ar1/ar2

array([[1.        , 1.        , 3.        ],
       [0.8       , 1.25      , 3.        ],
       [1.        , 1.33333333, 2.25      ]])

In [52]:
np.sqrt(ar1)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [53]:
np.sum(ar1)

np.int64(45)

In [54]:
np.where(ar1>=5)

(array([1, 1, 2, 2, 2]), array([1, 2, 0, 1, 2]))

In [55]:
np.count_nonzero(ar1)

9

In [56]:
np.nonzero(ar1)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1, 2]))